# Generated by Django 2.1.7 on 2019-03-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datagen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
