# Generated by Django 2.1.7 on 2019-03-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datagen', '0002_auto_20190318_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='commands',
        ),
        migrations.AddField(
            model_name='service',
            name='commands',
            field=models.ManyToManyField(to='datagen.Command'),
        ),
    ]
