# Generated by Django 2.2 on 2019-04-25 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datagen', '0005_auto_20190327_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='commands',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='service',
        ),
        migrations.AddField(
            model_name='attack',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attack',
            name='parameters',
            field=models.ManyToManyField(to='datagen.Parameter'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 25, 18, 4, 17, 862032), verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 25, 14, 4, 17, 862006), verbose_name='start'),
        ),
    ]
