# Generated by Django 2.1.7 on 2019-03-18 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bias', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200, unique=True)),
                ('mac', models.CharField(max_length=200, unique=True)),
                ('actions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagen.Action')),
                ('attacks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagen.Attack')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200, unique=True)),
                ('mac', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('commands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagen.Command')),
            ],
        ),
        migrations.CreateModel(
            name='Vm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200, unique=True)),
                ('mac', models.CharField(max_length=200, unique=True)),
                ('actions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagen.Action')),
                ('behavior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagen.Behavior')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagen.Service')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='vms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagen.Vm'),
        ),
        migrations.AddField(
            model_name='command',
            name='parameters',
            field=models.ManyToManyField(to='datagen.Parameter'),
        ),
        migrations.AddField(
            model_name='bias',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagen.Service'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='bias',
            field=models.ManyToManyField(to='datagen.Bias'),
        ),
        migrations.AddField(
            model_name='attack',
            name='commands',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagen.Command'),
        ),
        migrations.AddField(
            model_name='attack',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagen.Service'),
        ),
        migrations.AddField(
            model_name='action',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagen.Parameter'),
        ),
    ]
