# Generated by Django 2.1.7 on 2019-03-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datagen', '0003_auto_20190327_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hackers', models.ManyToManyField(to='datagen.Hacker')),
                ('vms', models.ManyToManyField(to='datagen.Vm')),
            ],
        ),
        migrations.RemoveField(
            model_name='machine',
            name='vms',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
