# Generated by Django 2.1.7 on 2019-03-27 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datagen', '0004_auto_20190327_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 19, 8, 7, 355762), verbose_name='end'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='max_actions',
            field=models.IntegerField(default=500, verbose_name="nombre d'actions maximum par vms"),
        ),
        migrations.AddField(
            model_name='experiment',
            name='nb_hackers',
            field=models.IntegerField(default=1, verbose_name='nombre de hackers'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='nb_vms',
            field=models.IntegerField(default=4, verbose_name='nombre de vms'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='network',
            field=models.GenericIPAddressField(default='192.168.10.0'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 15, 8, 7, 355721), verbose_name='start'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
