# Generated by Django 2.2 on 2019-04-25 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datagen', '0008_auto_20190425_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 25, 19, 9, 5, 332537), verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='hackers',
            field=models.ManyToManyField(blank=True, to='datagen.Hacker'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 25, 15, 9, 5, 332511), verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='vms',
            field=models.ManyToManyField(blank=True, to='datagen.Vm'),
        ),
    ]
